name: checkout_action_1
on: push
jobs:
    checkout_action_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v6
        - name: Welcome message
          run: echo "Cheers to github Actions learning !!"
        - name: Listing files
          run: ls -lart
        - name: Read README
          run: cat README.md
        - name: install tree pkg
          run: sudo apt install tree -y
        - name: check current dir
          run: pwd
        - name: Listing files
          run: tree .