name: my first workflow_2
on: push
jobs:
    first_job_2:
        runs-on: ubuntu-latest
        steps:
          - name: clone the repo
            run: git clone https://github.com/arupgitHubB/gh-actions-2.git gitrepo
          - name: Welcome message
            run: echo "Cheers to github Actions learning !!"
          - name: Listing files
            run: ls -lart gitrepo
          - name: Read README
            run: cat gitrepo/README.md
          - name: install tree pkg
            run: apt install tree -y
          - name: Listing files
            run: tree gitrepo