# Here env vars for generic vars like DOCKERHUB_URL and IMAGE_NAME
# defined like ${{ env.DOCKERHUB_URL }}
# Other vars we have put in repository level secrets and variables
# defined like ${{ vars.DOCKER_USERNAME}} and ${{ secrets.DOCKER_PWD }}


name: repository level secrets and variables
on: push
env:
  DOCKERHUB_URL: "docker.io"
  IMAGE_NAME: "my-app"
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repo
            uses: actions/checkout@v6
          - name: login to docker
            run: echo "docker login -u ${{ vars.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PWD }}"
          - name: build the docker image
            run: echo "docker build -t ${{ env.DOCKERHUB_URL }}/${{ vars.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest ."
    
    deploy_job:
        needs:
          - build_job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v6
        - name: push the image to repo
          run: echo "docker push ${{ env.DOCKERHUB_URL }}/${{ vars.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest"