name: timeout job level
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
    trigger_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Cheers to github Actions learning !!"
        - name: print time
          run: date
    deploy_job:
        needs: trigger_job
        runs-on: ubuntu-latest
        timeout-minutes: 2 # timeout after 2 mins for this entire job
        steps:
        - name: Print message
          run: echo "Deploying... Hang on !!"
        - name: sleeping
          run: sleep 180